service: line-api-study-golang

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  app:
    handler: bin/main
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# resources:
#   Resources:
#     DynamoDbTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: user_id
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: user_id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: "${self:provider.stage}-ddb-diagnosis"