service: line-api-study-golang

plugins:
  - serverless-offline

custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./conf/dev/dev.yml)}

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  bot:
    handler: bin/main
    environment:
      CHANNEL_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.environment.${self:provider.stage}.CHANNEL_TOKEN}

    events:
      - http:
          path: callback
          method: post
          cors: true

# resources:
#   Resources:
#     DynamoDbTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: user_id
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: user_id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: "${self:provider.stage}-ddb-diagnosis"